import { KrakendeTrait } from './types';

export const DEFAULT_POSITIVE_TRAITS: KrakendeTrait[] = [
  { id: 'p01', nl: 'Weloverwogen Kieskeurig', en: 'Thoughtfully Selective' },
  { id: 'p02', nl: 'Lekker Lang Luisterend Oor', en: 'Great Listener' },
  { id: 'p03', nl: 'Magnetisch Charismatisch', en: 'Magnetically Charismatic' },
  { id: 'p04', nl: 'Onstuitbaar Sportief', en: 'Unstoppably Sporty' },
  { id: 'p05', nl: 'Betonhard Besluitvaardig', en: 'Rock-Solid Decisive' },
  { id: 'p06', nl: 'Krankzinnig Creatief', en: 'Insanely Creative' },
  { id: 'p07', nl: 'Zeer Zelfverzekerd', en: 'Supremely Confident' },
  { id: 'p08', nl: 'Geweldig Geduldig', en: 'Amazingly Patient' },
  { id: 'p09', nl: 'Lekker ding', en: 'Total Hottie' },
  { id: 'p10', nl: 'Fantastisch Feestbeest', en: 'Fantastic Party Animal' },
  { id: 'p11', nl: 'Pietje Perfectionist', en: 'Little Mr/Ms Perfect' },
  { id: 'p12', nl: 'Niet te houden Spontaan', en: 'Unstoppably Spontaneous' },
  { id: 'p13', nl: 'Grappen-maker', en: 'Joker' },
  { id: 'p14', nl: 'Behoorlijk Betrouwbaar', en: 'Seriously Reliable' },
  { id: 'p15', nl: 'Verassend Inventief', en: 'Surprisingly Inventive' },
  { id: 'p16', nl: 'Cool en Kalm', en: 'Cool and Calm' },
  { id: 'p17', nl: 'Super Stressbestendig', en: 'Super Stress-Proof' },
  { id: 'p18', nl: 'Lekker Enthousiast', en: 'Wonderfully Enthusiastic' },
  { id: 'p19', nl: 'Sexueel Actief', en: 'Sexually Active' },
  { id: 'p20', nl: 'Altijd Ambitieus', en: 'Always Ambitious' },
  { id: 'p21', nl: 'Hyper Nauwkeurig', en: 'Hyper Precise' },
  { id: 'p22', nl: 'Zeldzaam Zorgzaam', en: 'Rarely Caring' },
  { id: 'p23', nl: 'O Zo Lief', en: 'Oh So Sweet' },
  { id: 'p24', nl: 'Dijk van een Doorzetter', en: 'Incredible Perseverer' },
];

export const DEFAULT_NEGATIVE_TRAITS: KrakendeTrait[] = [
  { id: 'n01', nl: 'Absurd Bizar', en: 'Absurdly Bizarre' },
  { id: 'n02', nl: 'Rampzalig Onhandig', en: 'Disastrously Clumsy' },
  { id: 'n03', nl: 'Onbedaarlijk Hysterisch', en: 'Uncontrollably Hysterical' },
  { id: 'n04', nl: 'Krenterig Gierig', en: 'Stingily Cheap' },
  { id: 'n05', nl: 'Weelderig Lui', en: 'Luxuriously Lazy' },
  { id: 'n06', nl: 'Baldadig Overmoedig', en: 'Recklessly Bold' },
  { id: 'n07', nl: 'Onbeheerst Driftig', en: 'Uncontrollably Hot-Headed' },
  { id: 'n08', nl: 'Genadeloos Streng', en: 'Mercilessly Strict' },
  { id: 'n09', nl: 'Driest Driftig', en: 'Fiercely Impulsive' },
  { id: 'n10', nl: 'Gruwelijk Moeilijk', en: 'Terribly Difficult' },
  { id: 'n11', nl: 'Chronische Zeikerd', en: 'Chronic Complainer' },
  { id: 'n12', nl: 'Meedogenloze Bitch', en: 'Ruthless Bitch' },
  { id: 'n13', nl: 'Complete Chaoot', en: 'Complete Chaos' },
  { id: 'n14', nl: 'Kriebelig Onrustig', en: 'Restlessly Fidgety' },
  { id: 'n15', nl: 'Notoir Sexverslaafd', en: 'Notoriously Sex-Addicted' },
  { id: 'n16', nl: 'Lamlendig Passief', en: 'Limply Passive' },
  { id: 'n17', nl: 'Lazy Laatkomer', en: 'Lazy Latecomer' },
  { id: 'n18', nl: 'Rampzalig Slordig', en: 'Disastrously Sloppy' },
  { id: 'n19', nl: 'Pijnlijk Overgevoelig', en: 'Painfully Oversensitive' },
  { id: 'n20', nl: 'Onuitstaanbaar Eigenwijs', en: 'Unbearably Stubborn' },
  { id: 'n21', nl: 'Meedogenloos Dominant', en: 'Ruthlessly Dominant' },
  { id: 'n22', nl: 'Neurotisch Gehaast', en: 'Neurotically Rushed' },
  { id: 'n23', nl: 'Hermetisch Gesloten', en: 'Hermetically Closed Off' },
  { id: 'n24', nl: 'Onbeschoft Brutaal', en: 'Shamelessly Rude' },
];
